name: Test

on:
  push:
    branches: [ main ]

jobs:

  deployment:
    name: Test Foramtion Devops
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm install
        
      - name: Install mocha
        run: npm install -g mocha
        
      - name: Run All Node.js Tests
        run: npm run test